# Generated by Django 2.0.5 on 2018-11-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileindb', '0005_auto_20181117_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examtype',
            name='examtype',
        ),
        migrations.AddField(
            model_name='examtype',
            name='exam_type',
            field=models.CharField(choices=[('lab', 'LAB'), ('mid1', 'MID1'), ('mid2', 'MID2'), ('project', 'PROJECT'), ('end_sem', 'END_SEM')], default='mid1', max_length=20),
        ),
    ]
