# Generated by Django 2.0.5 on 2018-11-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_auto_20181118_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherpost',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('publish', 'Publish')], default='publish', max_length=10),
        ),
    ]
