# Generated by Django 2.0.5 on 2018-12-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0015_auto_20181212_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherpost',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('publish', 'Publish')], default='publish', max_length=10),
        ),
    ]
