# Generated by Django 2.1.3 on 2018-11-16 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fileindb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='exam',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='fileindb.examtype'),
            preserve_default=False,
        ),
    ]
