# Generated by Django 2.1.3 on 2018-11-18 03:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('course_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('course_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='examtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_marks', models.CharField(max_length=50)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_dash.course')),
            ],
        ),
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proff_name', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileupload', models.FileField(unique=None, upload_to='static', validators=[django.core.validators.FileExtensionValidator(['csv'])])),
            ],
        ),
        migrations.CreateModel(
            name='table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100)),
                ('student_name', models.CharField(max_length=100)),
                ('marks', models.CharField(max_length=250)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_dash.course')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_dash.examtype')),
                ('proff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_dash.faculty')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='proff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_dash.faculty'),
        ),
    ]
