# Generated by Django 2.1.3 on 2018-11-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_dash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtype',
            name='exam_type',
            field=models.CharField(choices=[('5', 'END'), ('2', 'MID2'), ('3', 'PROJECT'), ('1', 'MID1'), ('4', 'LAB')], default=2, max_length=20),
        ),
    ]
