# Generated by Django 2.1.3 on 2018-11-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_dash', '0003_auto_20181118_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examtype',
            name='exam_type',
            field=models.CharField(choices=[('1', 'MID1'), ('3', 'PROJECT'), ('5', 'END'), ('4', 'LAB'), ('2', 'MID2')], default=2, max_length=20),
        ),
    ]
