# Generated by Django 2.1.3 on 2018-11-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_dash', '0004_auto_20181118_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examtype',
            name='exam_type',
            field=models.CharField(choices=[('3', 'PROJECT'), ('2', 'MID2'), ('5', 'END'), ('1', 'MID1'), ('4', 'LAB')], default=2, max_length=20),
        ),
    ]
