# Generated by Django 2.1.3 on 2018-11-18 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_dash', '0012_auto_20181118_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examtype',
            name='exam_type',
        ),
    ]
