# Generated by Django 2.1.3 on 2018-11-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_dash', '0014_examtype_exam_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examtype',
            name='exam_type',
            field=models.CharField(choices=[('6', 'attendence'), ('4', 'LAB'), ('1', 'MID1'), ('5', 'END'), ('2', 'MID2'), ('3', 'PROJECT')], default='2', max_length=20),
        ),
    ]
