# Generated by Django 2.1.3 on 2018-11-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_dash', '0016_auto_20181118_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examtype',
            name='exam_type',
            field=models.CharField(choices=[('mid2', 'MID2'), ('mid1', 'MID1'), ('project', 'PROJECT'), ('end', 'END'), ('lab', 'LAB')], default='mid1', max_length=20),
        ),
    ]
