# Generated by Django 2.1.3 on 2018-11-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_dash', '0017_auto_20181118_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentattendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100)),
                ('attendence', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='examtype',
            name='exam_type',
            field=models.CharField(choices=[('end', 'END'), ('mid2', 'MID2'), ('project', 'PROJECT'), ('lab', 'LAB'), ('mid1', 'MID1')], default='mid1', max_length=20),
        ),
    ]
