# Generated by Django 2.1.3 on 2018-11-18 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_dash', '0020_auto_20181118_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentattendence',
            name='student_id',
        ),
        migrations.AddField(
            model_name='table',
            name='attendence',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student_dash.studentattendence'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='examtype',
            name='exam_type',
            field=models.CharField(choices=[('mid1', 'MID1'), ('mid2', 'MID2'), ('end', 'END'), ('project', 'PROJECT'), ('lab', 'LAB')], default='mid1', max_length=20),
        ),
    ]
