# Generated by Django 2.1.3 on 2018-11-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_dash', '0022_auto_20181118_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examtype',
            name='exam_type',
            field=models.CharField(choices=[('end', 'END'), ('lab', 'LAB'), ('project', 'PROJECT'), ('mid2', 'MID2'), ('mid1', 'MID1')], default='mid1', max_length=20),
        ),
    ]
