# Generated by Django 2.0.5 on 2018-11-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileindb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='table',
            name='student_id',
            field=models.CharField(max_length=100),
        ),
    ]
