# Generated by Django 2.0.5 on 2018-11-17 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileindb', '0004_auto_20181117_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtype',
            name='examtype',
            field=models.CharField(choices=[('project', 'PROJECT'), ('mid2', 'MID2'), ('end_sem', 'END_SEM'), ('lab', 'LAB'), ('mid1', 'MID1')], default='mid1', max_length=20),
        ),
        migrations.AlterField(
            model_name='file',
            name='fileupload',
            field=models.FileField(unique=None, upload_to='static', validators=[django.core.validators.FileExtensionValidator(['csv'])]),
        ),
    ]
