# Generated by Django 2.0.5 on 2018-11-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileindb', '0006_auto_20181117_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examtype',
            name='exam_type',
            field=models.CharField(choices=[(2, 'MID2'), (1, 'MID1'), (4, 'PROJECT'), (3, 'LAB'), (5, 'END_SEM')], default=1, max_length=20),
        ),
    ]
