# Generated by Django 2.0.5 on 2018-11-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileindb', '0015_auto_20181118_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examtype',
            name='exam_type',
            field=models.CharField(choices=[('2', 'MID2'), ('4', 'LAB'), ('3', 'PROJECT'), ('5', 'END'), ('1', 'MID1')], default=2, max_length=20),
        ),
    ]
