# Generated by Django 2.0.5 on 2018-12-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileindb', '0016_auto_20181118_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examtype',
            name='exam_type',
            field=models.CharField(choices=[('1', 'MID1'), ('4', 'LAB'), ('2', 'MID2'), ('3', 'PROJECT'), ('5', 'END')], default=2, max_length=20),
        ),
    ]
