# Generated by Django 2.0.5 on 2018-12-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileindb', '0017_auto_20181208_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examtype',
            name='exam_type',
            field=models.CharField(choices=[('4', 'LAB'), ('3', 'PROJECT'), ('2', 'MID2'), ('1', 'MID1'), ('5', 'END')], default=2, max_length=20),
        ),
    ]
