# Generated by Django 2.0.5 on 2018-12-11 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileindb', '0018_auto_20181210_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examtype',
            name='exam_type',
            field=models.CharField(choices=[('2', 'MID2'), ('5', 'END'), ('3', 'PROJECT'), ('1', 'MID1'), ('4', 'LAB')], default=2, max_length=20),
        ),
    ]
