# Generated by Django 2.0.5 on 2018-12-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileindb', '0020_auto_20181212_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examtype',
            name='exam_type',
            field=models.CharField(choices=[('1', 'MID1'), ('5', 'END'), ('4', 'LAB'), ('2', 'MID2'), ('3', 'PROJECT')], default=2, max_length=20),
        ),
    ]
