# Generated by Django 2.0.5 on 2018-12-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileindb', '0021_auto_20181212_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examtype',
            name='exam_type',
            field=models.CharField(choices=[('4', 'LAB'), ('5', 'END'), ('1', 'MID1'), ('2', 'MID2'), ('3', 'PROJECT')], default=2, max_length=20),
        ),
    ]
