# Generated by Django 2.1.3 on 2018-11-11 20:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('CommentsId', models.AutoField(primary_key=True, serialize=False)),
                ('Comments', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('QuestionId', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=1000)),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('RepliesId', models.AutoField(primary_key=True, serialize=False)),
                ('Replies', models.CharField(max_length=1500)),
                ('CommentsId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forum.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('SolutionsId', models.AutoField(primary_key=True, serialize=False)),
                ('solutions', models.CharField(max_length=1500)),
                ('QuestionId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forum.Question')),
            ],
        ),
        migrations.DeleteModel(
            name='post',
        ),
        migrations.AddField(
            model_name='comment',
            name='SolutionsId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forum.Solution'),
        ),
    ]
