# Generated by Django 2.1.3 on 2018-11-17 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_question_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='Title',
            field=models.CharField(default='No title', max_length=200),
        ),
    ]
