# Generated by Django 2.0.5 on 2018-11-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileindb', '0008_auto_20181118_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examtype',
            name='exam_type',
            field=models.CharField(choices=[('5', 'END'), ('3', 'PROJECT'), ('4', 'LAB'), ('2', 'MID2'), ('1', 'MID1')], default=2, max_length=20),
        ),
    ]
